spring:
  application:
    name: Config-Dev
eureka:
  client:
    instance:
      preferIpAddress: true
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
